cart/urls.py
from django.conf.urls import url
from cart import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

project/urls.py
from iFood import views
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
 


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^cart/', include('cart.urls')),
    url(r'^iFood/', include('iFood.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]

#This is a add-to-cart-form mentioned in iFood.views
#It handles adding and updating item quantity in the cart
#User can add between 1 and 26 instances of each dish to the cart
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from iFood.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django.contrib.auth.decorators import login_required

#The cart views that are rendered in the cart template

#Cart add view
#Uses a require_POST decorator
#Gets product (dish) by dish id invoked in method declaration
#And adds it to the current cart (based on current session)
#Using the CartAdd.. form
@require_POST
@login_required(login_url = '/iFood/login/')
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')

#Cart remove view
#Removes product object from the current cart
@login_required(login_url = '/iFood/login/')
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

#Cart detail view
#Used to update the quantity of a particular product object
#In the current cart
@login_required(login_url = '/iFood/login/')
def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/cart.html', {'cart':cart})

templates/cart/cart.html
{% extends 'ifood/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %}
	Shopping Cart
{% endblock %}

{% block body_block %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<style>
	.container {
		position: relative;
	}

	.btn-default {
		background-color: #A19F9C;
		color: black;
	}

	.expiry-date-group {
		float: left;
		width: 50%;
	}

	.expiry-date-group input {
		width: calc(100% + 1px);
		border-top-right-radius: 0;
		border-bottom-right-radius: 0;
	}

	.expiry-date-group input:focus {
		position: relative;
		z-index: 10;
	}

	.security-code-group {
		float: right;
		width: 50%;
	}

	.security-code-group input {
		border-top-left-radius: 0;
		border-bottom-left-radius: 0;
	}

	.zip-code-group {
		clear: both;
	}

	.PayButton {
		outline: 0 !important;
		height: 42px;
		font-size: 16px;
		background-color: #54c7c3 !important;
		border: none;
	}

	#PayButton:hover {
		background-color: #6dcecb !important;
	}

	.inline {
		max-width: 350px;
		margin: 0 auto;
		width: 100%;
		/* Full width */
		height: 100%;
		/* Full height */
		overflow: auto;
		/* Enable scroll if needed */
		background-color: rgb(0, 0, 0);
		/* Fallback color */
		background-color: rgba(0, 0, 0, 0.4);
		/* Black w/ opacity */
		-webkit-animation-name: fadeIn;
		/* Fade in the background */
		-webkit-animation-duration: 0.4s;
		animation-name: fadeIn;
		animation-duration: 0.4s;
	}

	#Checkout {
		width: 50%;
		min-width: 300px;
		height: 100%;
		min-height: 100%;
		background: 0 0 #ffffff;
		border-radius: 8px;
		border: 1px solid #dedede;
		margin-left: auto;
		margin-right: auto;
		display: none;
		-webkit-animation-name: slideIn;
		-webkit-animation-duration: 0.4s;
		animation-name: slideIn;
		animation-duration: 0.4s;
		margin-bottom: 30px;
	}

	#Checkout>h1 {
		margin: 0;
		padding: 20px;
		text-align: center;
		background: #eef2f4;
		color: #5d6f78;
		font-size: 24px;
		font-weight: 300;
		border-bottom: 1px solid #dedede;
		border-top-left-radius: 8px;
		border-top-right-radius: 8px;
	}

	#Checkout>form {
		margin: 0 25px 25px;
	}

	label {
		color: #46545c;
		margin-bottom: 2px;
	}

	.input-container {
		position: relative;
	}

	.input-container input {
		padding-right: 25px;
	}

	.input-container>i, a[role="button"] {
		color: #d3d3d3;
		width: 25px;
		height: 30px;
		line-height: 30px;
		font-size: 16px;
		position: absolute;
		top: 2px;
		right: 2px;
		cursor: pointer;
		text-align: center;
	}

	.input-container>i:hover, a[role="button"]:hover {
		color: #777;
	}

	.amount-placeholder {
		font-size: 20px;
		height: 34px;
	}

	.amount-placeholder>button {
		float: right;
		width: 60px;
	}

	.amount-placeholder>span {
		line-height: 34px;
	}

	.card-row {
		text-align: center;
		margin: 0px 25px 10px;
	}

	.card-row i {
		font-size: 30px;
	}

	.card-row span {
		width: 48px;
		height: 30px;
		margin-right: 3px;
		background-repeat: no-repeat;
		display: inline-block;
		background-size: contain;
	}

	.align-middle {
		vertical-align: middle;
	}

	input {
		box-shadow: none !important;
	}

	input:focus {
		border-color: #b0e5e3 !important;
		background-color: #eef9f9 !important;
	}

	.close {
		color: #000000;
		font-size: 28px;
		font-weight: bold;
		padding: 0px 10px 0px 0px;
	}

	.close:hover, .close:focus {
		color: #000;
		text-decoration: none;
		cursor: pointer;
	}

	@-webkit-keyframes slideIn {
		from {
			bottom: -300px;
			opacity: 0;
		}
		to {
			bottom: 0;
			opacity: 1;
		}
	}

	@keyframes slideIn {
		from {
			bottom: -300px;
			opacity: 0;
		}
		to {
			bottom: 0;
			opacity: 1;
		}
	}

	@-webkit-keyframes fadeIn {
		from {
			opacity: 0;
		}
		to {
			opacity: 1;
		}
	}

	@keyframes fadeIn {
		from {
			opacity: 0;
		}
		to {
			opacity: 1;
		}
	}

	.table>tbody>tr>td, .table>tfoot>tr>td {
		vertical-align: middle;
	}

	.main-cart {
		margin: 0 auto;
	}

	.main-cart h1 {
		font-size: 35px;
		padding: 10px 40px;
	}

	.main-cart h2 {
		font-size: 20px;
		padding: 10px 40px;
	}

	@media screen and (max-width: 600px) {
		table#cart tbody td .form-control {
			width: 20%;
			display: inline !important;
		}
		.actions .btn {
			width: 36%;
			margin: 1.5em 0;
		}
		.actions .btn-info {
			float: left;
		}
		.actions .btn-danger {
			float: right;
		}
		table#cart thead {
			display: none;
		}
		table#cart tbody td {
			display: block;
			padding: 0.6rem;
			min-width: 320px;
		}
		table#cart tbody tr td:first-child {
			background: #333;
			color: #fff;
		}
		table#cart tbody td:before {
			content: attr(data-th);
			font-weight: bold;
			display: inline-block;
			width: 8rem;
		}
		table#cart tfoot td {
			display: block;
		}
		table#cart tfoot td .btn {
			display: block;
		}
	}
</style>
<body>
	<div class="container">
	 	<h1>Shopping Cart</h1>
		<h2>
			{% with total_items=cart|length %}
	        {% if cart|length > 0 %}
	        	My Order:
	        	<a href="{% url "cart:cart_detail" %}" style="color: #3124F1">
	            	{{ total_items }} item{{ total_items|pluralize }} - £
	            	{{ cart.get_total_price }}
	        	</a>
	        {% else %}
	        	Your cart is empty.
	        {% endif %}
	        {% endwith %}
		</h2>
	  	<table id="cart" class="table table-hover table-condensed">
	    	<thead>
	        	<tr>
			    	<th style="width:50%">Product</th>
			        <th style="width:10%">Price</th>
			        <th style="width:8%">Quantity</th>
			        <th style="width:22%" class="text-center">Subtotal</th>
			        <th style="width:10%">Remove</th>
	            </tr>
	         </thead>
	         <tbody>
	         	{% for item in cart %}
	            {% with product=item.product  %}
	            	<tr>
	        			<td data-th="Product">
	          				<div class="row">
	            				<div class="col-sm-10">
	              					<h4 class="nomargin">{{ product.name }}</h4>
	            				</div>
	          				</div>
	        			</td>
	        			<td data-th="Price">£{{ item.price }}</td>
	        			<td data-th="Quantity">
	        			<form action="{% url "cart:cart_add" product.id %}" method="post">
	         				{% csrf_token %}
	         				{{ item.update_quantity_form.quantity}}
	         				{{ item.update_quantity_form.update}}
	         				<button class="btn btn-info btn-sm" type="submit"><i class="fa fa-refresh"></i></button>
	        			</form>
	        			</td>
	        			<td data-th="Subtotal" class="text-center">£{{ item.total_price }}</td>
	        			<td class="actions" data-th="Remove">
							<a href="{% url "cart:cart_remove" product.id %}">
								<button class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></button>
							</a>                    
						</td>
	      			</tr>
	       		{% endwith %}
	       		{% endfor %}     
	      	<tfoot>
	        	<tr class="visible-xs">
	        		<td class="text-center"><strong>Total {{ cart.get_total_price }}</strong></td>
	        	</tr>
	        	<tr>
	         		<td><a href="{% url "index" %}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
	                <td colspan="2" class="hidden-xs"></td>
	          		<td class="hidden-xs text-center"><strong>Total: £{{ cart.get_total_price }}</strong></td>
	          		{% if cart|length > 0 %}
	          		<td>
	            		<button class="btn btn-success btn-block" id="myBtn" >Checkout <i class="fa fa-angle-right"></i></button>
	          		</td>
	         		{% endif %}
	          	</tr>
	        </tbody>
	      	</tfoot>
	    </table>
	    <h2> Check your order: <a href="{% url "my-order" %}"><button class="btn btn-default">My Order</button></a></h2>
	    <div id="Checkout" class="inline">
	    	<span class="close">&times;</span>
	  		<h1>Pay</h1>
	  		<form>
	  			<div class="zip-code-group form-group">
	    			<label for="ZIPCode">Delivery address :</label>
	  				<p>{{user.userprofile.address}}</p>
	    			<a href="{% url "account"%}">Edit address <i class="fa fa-edit"></i></a>
	 			</div>
	  		</form>
		  	<div class="card-row">
			    <i class="fa fa-cc-visa" style="color:navy;"></i>
			    <i class="fa fa-cc-amex" style="color:blue;"></i>
			    <i class="fa fa-cc-mastercard" style="color:red;"></i>
			    <i class="fa fa-cc-discover" style="color:orange;"></i>
		  	</div>
	  		<form>
				<div class="form-group">
			    	<label for="PaymentAmount">Payment amount</label>
			      	<div class="amount-placeholder">
			        	<span>£{{ cart.get_total_price }}</span>
			      	</div>
			    </div>
			    <div class="form-group">
			      	<label or="NameOnCard">Name on card</label>
			      	<input id="NameOnCard" class="form-control" type="text" maxlength="255" placeholder="John More Doe"required="required"></input>
			   	</div>
			    <div class="form-group">
			      	<label for="CreditCardNumber">Card number</label>
			      	<input id="CreditCardNumber" class="null card-image form-control" type="text" placeholder="1111-2222-3333-4444"required="required"></input>
			    </div>
			    <div class="expiry-date-group form-group">
			      	<label for="ExpiryDate">Expiry date</label>
			      	<input id="ExpiryDate" class="form-control" type="text" placeholder="MM / YY" maxlength="7" required="required"></input>
			    </div>
			    <div class="security-code-group form-group">
			      	<label for="SecurityCode">Security code</label>
			      	<div class="input-container">
			        	<input id="SecurityCode" class="form-control" type="text" placeholder="352" required="required"></input>
			      	</div>
			    </div>
			    <label>
			         <input type="checkbox" checked="checked" name="sameadr"> Shipping address same as billing
			    </label>
			    <div>
			    	<button type="submit" class="btn btn-block btn-success submit-button" id="PayButton" onclick="closeFormandGo()">
			     		£ {{ cart.get_total_price }} <i class="fa fa-lock"></i></button>
			 	</div>
			</form>
		</div>
	</div>
</body>
<script>
	var modal = document.getElementById("Checkout");
	
	var btn = document.getElementById("myBtn");
	
	var span = document.getElementsByClassName("close")[0];
	
	btn.onclick = function() {
	  modal.style.display = "block";
	}
	
	span.onclick = function() {
	  modal.style.display = "none";
	}
	
	function closeFormandGo() {
	    document.getElementById("Checkout").style.display = "none";
	    alert("Your order is being processed now!")
	    location.replace("{% url "my-order" %}");
	}
</script>
{% endblock %}