cart/urls.py
from django.conf.urls import url
from cart import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

iFood/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from iFood import views


#app_name = 'iFood'


urlpatterns = [ 
	url(r'^$', views.index, name='index'),
	url(r'about/$', views.about, name='about'),
	url(r'^signup/$',views.signup,name='signup'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^web-feedback/$', views.web_feedback, name='web-feedback'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^account/$', views.edit_profile, name ='account'),
	url(r'^my-order/$', views.my_order, name='my-order'),
	url(r'^restaurant-feedback/$', views.restaurant_feedback, name='restaurant-feedback'),
    url(r'^(?P<restaurant_name_slug>[\w\-]+)/$',
        views.show_restaurant, name='restaurant'),     
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from iFood import views
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
 


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^cart/', include('cart.urls')),
    url(r'^iFood/', include('iFood.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iFood/forms.py
from django import forms
from django.contrib.auth.models import User
from iFood.models import UserProfile, Feedback, Comments, Product, Restaurant, Order
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions

#The user form, based on django built-in User Model
#The __init__ helper is a crispy forms form helper
#Used while handling the form at signup
class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'First name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Last name'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'E-Mail'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':"8+ characters & please don't use your username as password"}))
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email','password')
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save person'))

#User profile form is an additional form for User signup
#Based on user profile model
#The helper is the same helper as in UserForm
class UserProfileForm(forms.ModelForm):
    address = forms.CharField(widget=forms.TextInput(attrs={'placeholder': '1234 Food Street'}))
    facebook = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'https://facebook.com/your-name'}))
    twitter = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'https://twitter.com/your-twitter-name'}))
    picture = forms.ImageField(required=False)
    class Meta:
        model = UserProfile
        fields = ('address','facebook','twitter','picture')
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save person'))

#The user profile edit form is a form for
#Editing user profile details for already registered users
class UserProfileEditForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('address','facebook','twitter','picture')

#The user profile edit form is a form for
#Editing user details (incl. password) for already registered users
class UserDetailsForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta:
        model = User
        fields = ('first_name','last_name','email','is_active')

#This form handles comments about the website itself
class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('comment','created_at')

class RestaurantFeedback(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ('restaurant','comment','user','created_at','rating')

iFood/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth import logout
from iFood.forms import UserForm, UserProfileForm, UserProfileEditForm
from iFood.forms import UserDetailsForm, FeedbackForm, RestaurantFeedback
from django.contrib import messages
from django.shortcuts import render, redirect
from django.shortcuts import render_to_response
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit
from django.shortcuts import get_object_or_404
from iFood.models import Restaurant, Product, OrderItem, Order, Feedback
from cart.forms import CartAddProductForm
from cart.cart import Cart
from django.core.files.storage import FileSystemStorage
from django.core.mail import send_mail 

#The index page view 
def index(request):
    restaurant_list = Restaurant.objects.order_by('-rating')[:5]
    context_dict = {'restaurants' : restaurant_list}
    response = render(request, 'iFood/index.html',context = context_dict)
    return response

#The about page view
def about(request):
   context_dict = {'boldmessage' : "Welcome "}
   response = render(request, 'iFood/about.html',context = context_dict)
   return response

#The signup page view, renders two forms corresponding to User
#and UserProfile models
#Automatic log-in after successful sign-up feature added
#To facilitate and "smoothen" the process
def signup(request):
   registered = False
   template_name = 'iFood/signup.html'
   if request.method == 'POST':
      user_form = UserForm(data=request.POST)
      profile_form = UserProfileForm(request.POST,request.FILES)
      if user_form.is_valid() and profile_form.is_valid():
         user = user_form.save()
         user.set_password(user.password)
         user.save()
         profile = profile_form.save(commit=False)
         profile.user = user
         if 'picture' in request.FILES:
             profile.picture = request.FILES['picture']
         profile.save()
         registered = True
         login(request,user)
      else:
         print(user_form.errors, profile_form.errors)

   else:
      user_form = UserForm()
      profile_form = UserProfileForm()
      
   return render(request, 'iFood/signup.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})

#Edit profile view
#Decorator used so that only logged in users can open the page
#Renders two forms that handle editing details of
#current user's details and user's userprofile
@login_required(login_url = '/iFood/login/')
def edit_profile(request):
    user = request.user
    form = UserDetailsForm(request.POST or None, instance=user)
    prof = UserProfileEditForm(request.POST or None, request.FILES, instance=user.userprofile)
    if request.method == 'POST':
        if form.is_valid() and prof.is_valid():
            # Save the changes but password
            form.save()
            if 'picture' in request.FILES:
                prof.picture = request.FILES['picture']
            prof.save()
            # Change password
            new_password = form.cleaned_data.get('password')
            if new_password:
                user.set_password(new_password)
            return HttpResponseRedirect(reverse('account'))
    context = {"form": form, "prof":prof}

    return render(request, "iFood/user-account.html", context)
   
#User log-in view
#Handles authentication of user using built-in
#Django authentication
#Logges user in or returns an error message
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username, password=password)
        
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account has been disabled!")
        else:
            messages.info(request,'Invalid login details supplied. Please try again or sign up.')
            return HttpResponseRedirect(reverse('login'))
    else:
        return render(request, 'iFood/login.html', {})
      
#Log out view
#Handles log out using built in django method
#Decorator needed, because only logged in users should
#be able to log out
@login_required(login_url = '/iFood/login/')     
def user_logout(request):
   logout(request)
   return HttpResponseRedirect(reverse('index'))

#The view handling comments logged-in users can add
#about the website itself
@login_required(login_url = '/iFood/login/')
def web_feedback(request):
   if request.method == 'POST':
       feedback_form = FeedbackForm(request.POST)
       if feedback_form.is_valid():
          feedback = feedback_form.save()
          feedback.save()
          return redirect('about')
   else:
       feedback_form = FeedbackForm()
   return render(request, 'iFood/web-feedback.html',{'feedback_form':feedback_form})

@login_required(login_url = '/iFood/login/')
def restaurant_feedback(request):
    if request.method == 'POST':
        restaurant_feedback = RestaurantFeedback(request.POST)
        if restaurant_feedback.is_valid():
            res_feedback = restaurant_feedback.save()
            res_feedback.save()
            return redirect('account')
    else:
        restaurant_feedback = RestaurantFeedback()
    return render(request, 'iFood/restaurant-feedback.html', 
                      {'restaurant_feedback':restaurant_feedback})
        
#The restaurant view that handles all restaurant's pages
#and their menus using the slug
#invokes product_detail method which handles the add-to-cart
#form. The add to cart feature only available to logged-in users
def show_restaurant(request, restaurant_name_slug):
    context_dict = {}
    try:
        restaurant = get_object_or_404(Restaurant,slug=restaurant_name_slug)
        dishes = Product.objects.filter(restaurant=restaurant)
        rest_feedback = Feedback.objects.filter(restaurant=restaurant)
        context_dict['feedback'] = rest_feedback
        context_dict['restaurant'] = restaurant
        context_dict['dishes'] = dishes            
        for dish in dishes:
            form = product_detail(request, id=dish.id, slug=dish.slug)
            context_dict['form'] = form
    except restaurant.DoesNotExist:
        context_dict['restaurant'] = None
        context_dict['dishes'] = None
        context_dict['feedback'] = None
    return render(request, 'iFood/restaurant.html', context_dict)

def show_feedback(request, restaurant_name):
    feedback = Feedback(request)
    rest_feedback = Feedback.objects.filter(restaurant=restaurant)
    context_dict ={'feedbacks':rest_feedback}
    return context_dict

#A helper method to the restaurant site that invokes add-to-cart
#form (see cart.forms) in the menus
def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form}
    return cart_product_form
   
def contact(request):
    return render(request, 'iFood/contact.html',{})

#The my order view that handles creating new Order objects
#After the user has confirmed the order and paid and clears the cart
#Displays the most current order  -> the order that was just created
#Sends user email with receipt and prints receipt to terminal
#If the request is not POST (so any case user goes to my-order)
#Not through the confirmation button
#The current order is selected by finding order with highest number
#(The most recent) from user's orders and displays its details
@login_required(login_url = '/iFood/login/')
def my_order(request):
   user = request.user
   context = {}
   cart = Cart(request)
   #The object is created HERE
   #if the method is post so if the button is clicked
   if request.method == 'POST':
      order = Order.objects.create(user=request.user)
      for item in cart:
         OrderItem.objects.create(order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity'])
      cart.clear()
      context['order'] = order
      my_orders = Order.objects.filter(user=request.user)
      l = []
      for o in my_orders:
         l.append(o.id)
      current = get_object_or_404(Order, id=max(l))
      order_items = OrderItem.objects.filter(order=current)
      context['my_orders']= my_orders
      context['order_items']=order_items
      context['current']=current
      #The terminal receipt
      print("--------------------------------------")
      print("This is your order's receipt\n\n")
      print("Order ID: ", current, "\nOrder date: ", current.created)
      print("--------------------------------------")
      total = 0
      for item in order_items:
         print(item.product.name, "---- £",item.product.price, " x ", item.quantity)
         total += (item.product.price * item.quantity)
      print("Total cost:", total)
      print("--------------------------------------")
      print("\n\nTHANK YOU FOR USING IFOOD. SEE YOU SOON!\n\n\n")
      print("iFood - Eat whatever you want! - www.pythonanywhere.com/iFood\n\n\n")  
      #The email receipt
      if user.email:
         mail_body = "Hi, this is your e-receipt for order: " + str(current) + "\nOrder date: "+ str(current.created) + "\nTotal cost: £" + str(total)
         send_mail('Your iFood receipt',mail_body,
                   '2312052D@student.gla.ac.uk',[user.email],)
   else:
         my_orders = Order.objects.filter(user=request.user)
         l = []

templates/iFood/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	<head lang="en">      
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>
	    	{% block title_block %}
			{% endblock %}
		</title>
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
		<style>
			body {
				font-family: 'Open Sans', sans-serif;
				font-weight: 400;
				margin: 0;
				padding: 0 15px 30px 15px;
				box-sizing: border-box;
				background: #FFFFFF;
			}
			.static-header {
				max-width: 100%;
				overflow: hidden;
				box-sizing: border-box;
				margin: 5px auto;
				text-align: left;
			}
			.static-header .nav {
				padding: 5px;
				max-width: 100%;
			}
			.static-header .nav img {
				float: left;
				height: 40px;
				width: auto;
				padding: 0px 5px 5px 0px;
			}
			.static-header .nav a {
				padding: 5px 5px 0px 0px;
				display: inline-block;
				color: #666666;
				text-decoration: none;
				font-size: 25px;
				cursor: pointer;
				float: right;
			}
			.static-header .nav a.logo {
				float: left;
			}
			.static-header .nav a:not(:last-of-type) {
				padding-left: 20px;
			}
			.static-header .nav a:hover {
				color: #333333;
			}
			.fixed-header {
				display: none;
				position: fixed;
				top: 0;
				background: #FFFFFF;
				margin: 0 -15px;
				width: 100%;
				border-bottom: 1px solid #CCCCCC;
				box-sizing: border-box;
				box-shadow: 0px 0px 10px 0 rgba(#000000, 0.5);
				opacity: 0.9;
				z-index: 100;
			}
			.fixed-header .fheader__container {
				max-width: 100%;
				padding: 10px 10px;
				margin: 0 auto;
				overflow: hidden;
				box-sizing: border-box;
			}
			.fixed-header .fheader__container .nav {
				max-width: 100%;
				text-align: left;
				padding: 0px 10px 0px 0px;
			}
			.fixed-header .fheader__container .nav img {
				float: left;
				height: 40px;
				width: auto;
				padding: 1px 5px;
			}
			.fixed-header .fheader__container .nav a {
				padding: 5px 5px 0px 0px;
				display: inline-block;
				color: #666666;
				text-decoration: none;
				font-size: 25px;
				cursor: pointer;
				float: right;
			}
			.fixed-header .fheader__container .nav a.logo {
				float: left;
				padding: 0px 2px 0px 0px;
			}
			.fixed-header .fheader__container .nav a:not(:last-of-type) {
				padding-left: 20px;
			}
			.fixed-header .fheader__container .nav a:hover {
				color: #333333;
			}
			.container__content {
				margin: 0 auto;
				max-width: 100%;
				background: rgba(255, 255, 255, 0.8);
				box-sizing: border-box;
				min-height: 100px;
				overflow: hidden;
				clear: both;
			}
			.footer {
				position: fixed;
				left: 0;
				bottom: 0;
				width: 100%;
				background-color: #696969;
				color: white;
				margin: 0;
				text-align: center;
				font-family: 'Open Sans', sans-serif;
				padding: 8px 10px;
			}
			.footer a {
				float: left;
				color: white;
				padding: 10px 10px;
				padding-right: 10px;
				font-size: 15px;
			}
			.footer a:hover {
				color: #D3D3D3;
			}
			.footer img {
				float: right;
				height: 40px;
				width: auto;
				padding: 0px 20px;
			}
		</style>
	</head>
	<body>
		<div class="static-header">
			<div class="nav">
				<a class="logo" href="{% url 'index' %}">
					<img src="{% static "images/icon.jpg" %}" height="40" />
				</a>
				<a class="logo" href="{% url 'index' %}">Home</a>
				{% if user.is_authenticated %}
					<a href="{% url 'logout' %}">Log Out</a>
					<a href="{% url 'account' %}">{{ user.username }}</a>
					<a href="{% url "cart:cart_detail" %}"><i class="fas fa-shopping-cart"></i></a>
				{% else %}
					<a href="{% url 'signup' %}">Sign Up</a>
					<a href="{% url 'login' %}">Sign In</a>
				{% endif %}
			</div>
		</div>
		<div class="fixed-header">
			<div class="fheader__container">
				<div class="nav">
					<a class="logo" href="{% url 'index' %}">
						<img src="{% static "images/icon.jpg" %}" height="40" />
					</a>
					<a class="logo" href="{% url 'index' %}">Home</a>
					{% if user.is_authenticated %}
						<a href="{% url 'logout' %}">Log Out</a>
						<a href="{% url 'account' %}">{{ user.username }}</a>
						<a href="{% url "cart:cart_detail" %}"><i class="fas fa-shopping-cart"></i></a>
					{% else %}
						<a href="{% url 'signup' %}">Sign Up</a>
						<a href="{% url 'login' %}">Sign In</a>
					{% endif %}
				</div>
			</div>
		</div>
		<div class="container__content">
			{% block body_block %}
			{% endblock %}
		</div>
		<div class="footer">
			<div>
				<a href="{% url 'about' %}">About Us</a>
				<a href="{% url 'contact' %}">Contact Us</a>
				<img src="{% static "images/icon2.jpg" %}" height="50" />
			</div>
		</div>
	</body>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
	<script>
	$(window).scroll(hfunction() {    
		var scroll = $(window).scrollTop();
	
		if (scroll >= 200) {
			$(".fixed-header").slideDown();
		} else {
			$(".fixed-header").slideUp();
		}
	});
	</script>
</html>

templates/iFood/contact.html
{% extends 'ifood/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Contact Us
{% endblock %} 

{% block body_block %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" />
<style>
	.contact {
		position: absolute;
		width: 100%;
		/*transform: translate(-50%);*/
		text-align: center;
	}
	.contact h1 {
		font-size: 40px;
		padding: 40px 0px 20px 0px;
	}
	.contact h2 {
		font-size: 15px;
		padding: 40px 0px 20px 0px;
	}
	.contact-method {
		width: 220px;
		height: 140px;
		display: inline-block;
		background: #4682B4;
		margin: 10px;
		color: #fff;
		position: relative;
		cursor: pointer;
	}
	.contact-method i {
		position: absolute;
		left: 0;
		top: 0;
		width: 100%;
		height: 100%;
		font-size: 40px;
		line-height: 140px;
		background: #34495e;
		z-index: 1;
		transition: transform 0.6s;
	}
	.contact-method span {
		position: absolute;
		width: 100%;
		left: 0;
		bottom: 0;
		padding: 10px 0;
	}
	.contact-method:hover i {
		transform: translateY(-40px);
	}
</style>
<body>
	<div class="contact">
		<h1>Contact Us :</h1>
		<div class="contact-method">
			<i class="fas fa-envelope"></i> <span>iFood-contact@gmail.com</span>
		</div>
		<div class="contact-method">
			<i class="fas fa-mobile-alt"></i> <span>+44 1234567890</span>
		</div>
		<div class="contact-method">
			<i class="fas fa-map-marker-alt"></i> <span>Glasgow, United Kingdom</span>
		</div>
		<h2>Feel free to contact us if you have any problem !</h2>
	</div>
</body>
{% endblock %} 

templates/iFood/restaurant.html
{% extends 'ifood/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load ratings %}

{% block title_block %}
    {{restaurant.name}}
{% endblock %}

{% block body_block %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Amatic SC'>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<style>    
	.container {
		padding: 60px;
		width: 100%;
	}
	.container .wrap-menu {
		display: table;
		width: 440px;
		max-width: 100%;
	}
	.container .wrap-menu .restaurant {
		width: 80%;
		margin: 0 auto;
		text-align: center;
		font-size: 36px;
		color: #cc9900;
	}
	.container .wrap-menu .restaurant .ic-cate {
		display: inline-block;
		width: 235px;
		height: 27px;
	}
	.container .wrap-menu img {
		width: 100%;
		height: auto;
		opacity: 0.3;
	}
	.container .wrap-menu .row-menu-wrap {
		margin-bottom: 35px;
	}
	.container .wrap-menu .row-menu-wrap .row-menu {
		display: table-row;
	}
	.container .wrap-menu .row-menu-wrap .row-menu .item-menu {
		display: table-cell;
		width: 90%;
		font-size: 21px;
		font-family: "yeseva";
		color: #cc9900;
	}
	.container .wrap-menu .row-menu-wrap .row-menu .item-prise {
		display: table-cell;
		font-size: 21px;
		font-family: "yeseva";
		color: #cc9900;
	}
	.gold-line {
		display: inline-block;
		width: 100%;
		height: 1px;
		margin-bottom: 8px;
		background-color: #cc9900;
	}
	.item-descr {
		font-size: 16px;
		font-family: "lato";
	}
	.btn {
		background-color: lightgray;
		padding-botton: 10px;
	}
	.form {
		text-align: left;
	}
	.rateRest {
		padding: 10px 0px 20px 0px;
	}
	.outer-wrapper {
		margin: 2%;
		position: relative;
		color: #737373;
		display: block;
		margin-bottom: 50px;
	}
	.outer-wrapper .box-wrapper {
		position: relative;
		padding: 0px 40px 0px 40px;
	}
	.outer-wrapper .box-wrapper .display-box {
		box-shadow: 1px 1px 2px 0px #C5C5C5;
		margin: 3%;
		padding: 0% 6%;
		border: 1px solid #C5C5C5;
		position: relative;
		top: 0;
		left: 0;
		color: #000;
		text-align: center;
	}
	.outer-wrapper .box-wrapper .display-box h3 {
		font-size: 25px;
	}
	.outer-wrapper .box-wrapper .display-box .content {
		font-size: 15px;
		text-align: left;
		margin-bottom: 5%;
		border-bottom: 1px solid #C5C5C5;
	}
	.outer-wrapper .box-wrapper .display-box .content li {
		list-style-type: none;
		padding: 3px;
	}
</style>
<body>
	<div class="container">
		<div class="col-md-5 left">
			<div class="wrap-menu">
	      		{% if restaurant %}
	      			<h2 class="restaurant">
		        		<span>{{restaurant.name}}</span>
		        		<i class="ic-cate"></i>
	      			</h2>
	      			{% if dishes %} 
	      				{% for dish in dishes %}
	      					<div class="row-menu-wrap">
		        				<div class="row-menu">
		          					<p class="item-menu">{{dish.name}}</p>
		          					<span href="#" class="item-prise">£{{dish.price}}</span>
		        				</div>
	        					<span class="gold-line"></span>
	        					<span class="item-descr">{{dish.description}}</span>
	        					{% if user.is_authenticated %}
									<form action="{% url 'cart:cart_add' product_id=dish.id %}" method="post">
										{% csrf_token %}
										<button type="submit" class="btn">Add to cart <i class="fas fa-cart-plus"></i></button>
										{{ form.quantity }}
									</form>
	        					{% endif %}
	      					</div>
	      				{% endfor %} 
	      			{% endif %} 
	      		{% endif %}
	    	</div>
	  	</div>
	  	<div class="col-md-5 right">
			<div class="wrap-menu">
		  		<img src="{% static "images/bg2.jpg" %}">
		 	</div>
	  	</div>
	  	<div class="rateRest">
	  		{% ratings restaurant %}
	  	</div>
	</div>
	<div class="outer-wrapper">
		<div class="box-wrapper">
			<div class="display-box">
	         	<h3>Users' Comments <i class="fas fa-comments"></i></h3>
	         	<hr>
	         	<div class="content">
	          	{% if restaurant %}
			    	{% if feedback %} 
			      	<ul>
				    	{% for feed in feedback %}
				      	<li>
				      		<i class="fas fa-quote-right"></i> {{ feed.comment }}
				     	</li>
				      	{% endfor %} 
				  	</ul>
				  	{% else %}
			      	<ul>
				      	<li>
				      		<i class="fas fa-quote-right"></i> No comment yet. Sign In to add comments!
				     	</li>
				  	</ul>
			      	{% endif %} 
				{% endif %} 
				</div>
	      	</div>
	   	</div>
	</div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}" type="text/javascript"></script>
{% endblock %}